[project]
name = "discord-watcher"
version = "0.1.0"
requires-python = ">=3.11,<3.13"
dependencies = [
    "discord.py==2.3.2",
    "requests==2.32.3",
    "python-dateutil==2.9.0.post0",
    "PyYAML==6.0.2",
]